### ISSUE TITLE
Issues with versioning bootstrap function

### ISSUE THREAD

**Issue by raininglemons** [VirtusLab/strapi-molecules#19]
On start up the application bombs out (when using Mongo as the DB):

```
Starting the development server...

Admin development at http://localhost:8000/admin/
[2020-09-18T16:04:56.477Z] error Bootstrap function in plugin "versioning" failed
[2020-09-18T16:04:56.479Z] error TypeError: knex.Schema.createTableIfNotExists is not a function
    at Object.<anonymous> (/XXX/strapi/node_modules/strapi-plugin-versioning/services/create-versions-table.js:46:22)
    at step (/XXX/strapi/node_modules/strapi-plugin-versioning/services/create-versions-table.js:33:23)
    at Object.next (/XXX/strapi/node_modules/strapi-plugin-versioning/services/create-versions-table.js:14:53)
```

**Comment by cyp3rius** [comment]
Hi @raininglemons, we will look onto that case. Can you please provide more details of env you're using?
